import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ scrollBehavior: 'smooth' }}
      >
        <nav className="w-full flex justify-center py-6 mb-8 bg-background/80 dark:bg-background/80 backdrop-blur-lg sticky top-0 z-50 border-b border-foreground/10">
          <ul className="flex gap-8 text-lg font-semibold">
            <li><a href="#home" className="hover:text-blue-500 transition-colors">Home</a></li>
            <li><a href="#about" className="hover:text-blue-500 transition-colors">About</a></li>
            <li><a href="#projects" className="hover:text-blue-500 transition-colors">Projects</a></li>
            <li><a href="#skills" className="hover:text-blue-500 transition-colors">Skills</a></li>
            <li><a href="#contact" className="hover:text-blue-500 transition-colors">Contact</a></li>
            <li><a href="/resume" className="hover:text-blue-500 transition-colors">Resume</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
